### ISSUE TITLE
SIGSEGV with latest dnote client and selfhosted server

### ISSUE THREAD

**Issue by kimusan** [dnote/dnote#602] opened 2022-05-11 12:22 UTC
When I try to login to my self-hosted server I get the following crash:

```
note login
  Welcome to Dnote Pro (https://notes.barbeque.tech)
  [?] email: kim@schulz.dk
  [?] password: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7905dc]

goroutine 1 [running]:
github.com/dnote/dnote/pkg/cli/client.Signin(0xc0000c6830, 0x9, 0xc0000c8240, 0x11, 0xc0000c8260, 0x16, 0xc0000c6840, 0x10, 0xc0000c6920, 0x10, ...)
	/ext-go/1/src/github.com/dnote/dnote/pkg/cli/client/client.go:529 +0x17c
github.com/dnote/dnote/pkg/cli/cmd/login.Do(0xc0000c6830, 0x9, 0xc0000c8240, 0x11, 0xc0000c8260, 0x16, 0xc0000c6840, 0x10, 0xc0000c6920, 0x10, ...)
	/ext-go/1/src/github.com/dnote/dnote/pkg/cli/cmd/login/login.go:60 +0x95
github.com/dnote/dnote/pkg/cli/cmd/login.newRun.func1(0xc00017c840, 0x1151080, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/dnote/dnote/pkg/cli/cmd/login/login.go:172 +0x3cd
github.com/spf13/cobra.(*Command).execute(0xc00017c840, 0x1151080, 0x0, 0x0, 0xc00017c840, 0x1151080)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x10f4860, 0xc0001437a8, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/dnote/dnote/pkg/cli/cmd/root.Execute(...)
	/ext-go/1/src/github.com/dnote/dnote/pkg/cli/cmd/root/root.go:39
main.main()
	/ext-go/1/src/github.com/dnote/dnote/pkg/cli/main.go:67 +0x79e

```
I have been running with this setup for a long time (since the server was version 0.1.1) but have mostly used the web interface (the one you have now unfortunately removed). 
Since I need my notes, I wanted to move to the cli, but then I get the above error. 

## Environment
Server running on ubuntu 20.04 
Cli running on other ubuntu 20.04  desktop

* project (cli, server, browser-extension): 
cli 

* version: 
cli version 0.12.0
server version 2.0.1

* operating system: 
ubuntu 20.04

**Comment by kimusan** [comment] 2022-05-11 12:31
just tested with cli v0.11.1 and the problem also exists there.

**Comment by sungwoncho** [comment] 2022-05-12 12:19
Hi @kimusan, I'll have a look sometime soon, in the meantime:

* does the problem persist with Dnote server [v1.0.4](https://github.com/dnote/dnote/releases/tag/server-v1.0.4)?
* could you try to set `apiEndpoint: [insert base url to your dnote instance]/api` in `.config/dnote/dnoterc`?

**Comment by kimusan** [comment] 2022-05-12 15:45
Seems to happen with both 1. 0.4 and 2.0.1 and both the old and new cli.
I wonder if it is the ngnix I have in front that somehow get it to break. The ssl cert is currently expired so maybe that can get things to explode.
The Web interface works just fine on the server.

Also tried with /api and also with :3000/api but no luck.

BTW: is it on purpose the new cli uses the old location for the dnotesrc file? I thought it was weird that it did not identify my changes when I changed the api url in ~/.config/dnote/dnoterc. Strace showed it tried to open ~/.dnote/dnoterc

**Comment by sungwoncho** [comment] 2022-05-14 10:42
> The ssl cert is currently expired

I think this is the root cause. I admit that the error handling could be improved, and opened #603 to track the improvement.

Would you be able to try to renew your SSL cert? Or you could use `http` rather than `https` to get unblocked in the short term.

> is it on purpose the new cli uses the old location for the dnotesrc file?

Yes, it is intentional for v0.12.0. If the old location exists, CLI will use that location for backward compatibility (https://github.com/dnote/dnote/blob/master/CHANGELOG.md#0120---2020-01-03).

**Comment by kimusan** [comment] 2022-05-23 12:47
Finally got around to test it with a new ssl cert (the nginx setup was a bit funky so it required a bit of a hack). This is indeed the problem causing the SIGSEGV and now I can login and search my notes again.

**Comment by sungwoncho** [comment] 2022-05-29 00:33
Thanks for the update. Closing this and keeping #603 open as an improvement.

More notes on the removal of the web interface: it was removed to lengthen the project's lifespan by simplifying the features and reducing complexity. Since API is stable, maybe a simplified version could be offered as a non-official client in the future. Please let me know about any thoughts.

**Closed by sungwoncho** 2022-05-29 00:33 UTC
